version: "3.3"

services:
  server:
    image: wb_bot:latest
    container_name: wb.bot
    hostname: wb_server
    env_file:
      - .env
    environment: 
    
      - ASPNETCORE_ENVIRONMENT=DevelopmentDocker
      - ASPNETCORE_URLS=http://*:8443
    build:
      context: ./
      dockerfile: ./Dockerfile.backend
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=WB
      - POSTGRES_USER=postgres
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host